server:
  port: 8100

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    pathmatch:
      # SpringBoot2.6整合Swagger3
      matching-strategy: ant_path_matcher

aliyun:

  # oss-cn-{area}.aliyuncs.com
  endpoint:
  bucket-name:
  access-key-id:
  access-key-secret:
