server:
  port: 8101

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8080

    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

      routes:
        - id: article
          uri: lb://article
          predicates:
            - Path=/article/**
          filters:
            - StripPrefix=1

        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
