server:
  port: 8003

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    pathmatch:
      # SpringBoot2.6整合Swagger3
      matching-strategy: ant_path_matcher

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: 9zHu2:HGqqB_G7s

  mail:
    host:
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: false
