server:
  port: 8004

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    pathmatch:
      # SpringBoot2.6整合Swagger3
      matching-strategy: ant_path_matcher

  application:
    name: search

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
